
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_CUSTOMER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8081


